"""initial schema

Revision ID: 13ece6158a32
Revises: 
Create Date: 2026-06-14 18:03:08.613934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ece6158a32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('client_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('assessment_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('flow1_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('flow2_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('flow3_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('flow4_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inflation_post', sa.Float(), nullable=True),
    sa.Column('roi_post', sa.Float(), nullable=True),
    sa.Column('inflation_pre', sa.Float(), nullable=True),
    sa.Column('roi_pre', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Float(), nullable=False),
    sa.Column('new_value', sa.Float(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculation_output',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('pf_monthly_rate', sa.Float(), nullable=False),
    sa.Column('real_rate', sa.Float(), nullable=False),
    sa.Column('real_rate_monthly', sa.Float(), nullable=False),
    sa.Column('monthly_eff_pre', sa.Float(), nullable=False),
    sa.Column('client_corpus', sa.Float(), nullable=False),
    sa.Column('client_pf_corpus', sa.Float(), nullable=False),
    sa.Column('client_net_corpus', sa.Float(), nullable=False),
    sa.Column('client_monthly_sip', sa.Float(), nullable=False),
    sa.Column('client_lump_sum', sa.Float(), nullable=False),
    sa.Column('spouse_corpus', sa.Float(), nullable=False),
    sa.Column('spouse_pf_corpus', sa.Float(), nullable=False),
    sa.Column('spouse_net_corpus', sa.Float(), nullable=False),
    sa.Column('spouse_monthly_sip', sa.Float(), nullable=False),
    sa.Column('spouse_lump_sum', sa.Float(), nullable=False),
    sa.Column('total_insurance_required', sa.Float(), nullable=False),
    sa.Column('total_goals_monthly_sip', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communication_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('spouse_mobile', sa.String(length=15), nullable=True),
    sa.Column('spouse_email', sa.String(length=120), nullable=True),
    sa.Column('residential_address', sa.Text(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('number_of_children', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('goal_type', sa.String(length=100), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('today_cost', sa.Float(), nullable=False),
    sa.Column('inflation_rate', sa.Float(), nullable=True),
    sa.Column('future_cost', sa.Float(), nullable=True),
    sa.Column('monthly_sip', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('client_name', sa.String(length=120), nullable=False),
    sa.Column('client_occupation', sa.String(length=120), nullable=False),
    sa.Column('client_designation', sa.String(length=120), nullable=False),
    sa.Column('client_company', sa.String(length=120), nullable=False),
    sa.Column('client_dob', sa.Date(), nullable=False),
    sa.Column('client_age', sa.Integer(), nullable=False),
    sa.Column('spouse_name', sa.String(length=120), nullable=True),
    sa.Column('spouse_occupation', sa.String(length=120), nullable=True),
    sa.Column('spouse_designation', sa.String(length=120), nullable=True),
    sa.Column('spouse_company', sa.String(length=120), nullable=True),
    sa.Column('spouse_dob', sa.Date(), nullable=True),
    sa.Column('spouse_age', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('child_number', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('occupation', sa.String(length=120), nullable=True),
    sa.Column('financially_dependent', sa.Boolean(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('calculated_age', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('calculation_id', sa.Uuid(), nullable=False),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_record.id'], ),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculation_output.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_log')
    op.drop_table('child')
    op.drop_table('personal_details')
    op.drop_table('goals')
    op.drop_table('family_details')
    op.drop_table('communication_details')
    op.drop_table('calculation_output')
    op.drop_table('rate_history')
    op.drop_table('rate_config')
    op.drop_table('assessment_record')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
