"""add performance indexes and caching support

Revision ID: b385026dad43
Revises: cb71d87a59f1
Create Date: 2026-06-27 18:24:18.002121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b385026dad43'
down_revision = 'cb71d87a59f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculation_output', schema=None) as batch_op:
        batch_op.create_index('ix_calculation_output_assessment_id', ['assessment_id'], unique=False)

    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.create_index('ix_child_family_id', ['family_id'], unique=False)

    with op.batch_alter_table('communication_details', schema=None) as batch_op:
        batch_op.create_index('ix_communication_details_assessment_id', ['assessment_id'], unique=False)

    with op.batch_alter_table('education_programs', schema=None) as batch_op:
        batch_op.create_index('ix_education_programs_level_course_country', ['level', 'course_category', 'country'], unique=False)

    with op.batch_alter_table('family_details', schema=None) as batch_op:
        batch_op.create_index('ix_family_details_assessment_id', ['assessment_id'], unique=False)

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index('ix_goals_assessment_id', ['assessment_id'], unique=False)

    with op.batch_alter_table('personal_details', schema=None) as batch_op:
        batch_op.create_index('ix_personal_details_assessment_id', ['assessment_id'], unique=False)

    with op.batch_alter_table('report_log', schema=None) as batch_op:
        batch_op.create_index('ix_report_log_assessment_id', ['assessment_id'], unique=False)

    with op.batch_alter_table('tour_destinations', schema=None) as batch_op:
        batch_op.create_index('ix_tour_destinations_country', ['country'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_destinations', schema=None) as batch_op:
        batch_op.drop_index('ix_tour_destinations_country')

    with op.batch_alter_table('report_log', schema=None) as batch_op:
        batch_op.drop_index('ix_report_log_assessment_id')

    with op.batch_alter_table('personal_details', schema=None) as batch_op:
        batch_op.drop_index('ix_personal_details_assessment_id')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index('ix_goals_assessment_id')

    with op.batch_alter_table('family_details', schema=None) as batch_op:
        batch_op.drop_index('ix_family_details_assessment_id')

    with op.batch_alter_table('education_programs', schema=None) as batch_op:
        batch_op.drop_index('ix_education_programs_level_course_country')

    with op.batch_alter_table('communication_details', schema=None) as batch_op:
        batch_op.drop_index('ix_communication_details_assessment_id')

    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.drop_index('ix_child_family_id')

    with op.batch_alter_table('calculation_output', schema=None) as batch_op:
        batch_op.drop_index('ix_calculation_output_assessment_id')

    # ### end Alembic commands ###
