"""add education and tour reference tables

Revision ID: cb71d87a59f1
Revises: 355fbae41eae
Create Date: 2026-06-24 17:21:03.844189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb71d87a59f1'
down_revision = '355fbae41eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_programs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('course_category', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('country_famous_for', sa.String(length=200), nullable=True),
    sa.Column('approx_cost_inr', sa.Float(), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('living_cost_included', sa.Boolean(), nullable=False),
    sa.Column('lifestyle_level', sa.String(length=100), nullable=True),
    sa.Column('inflation_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tour_destinations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('budget_inr', sa.Float(), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour_destinations')
    op.drop_table('education_programs')
    # ### end Alembic commands ###
