"""add education and tour links to goals

Revision ID: db08ccbfa999
Revises: b385026dad43
Create Date: 2026-06-27 22:24:34.870781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db08ccbfa999'
down_revision = 'b385026dad43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education_program_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('tour_destination_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_goals_tour_destination_id', 'tour_destinations', ['tour_destination_id'], ['id'])
        batch_op.create_foreign_key('fk_goals_education_program_id', 'education_programs', ['education_program_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_goals_education_program_id', type_='foreignkey')
        batch_op.drop_constraint('fk_goals_tour_destination_id', type_='foreignkey')
        batch_op.drop_column('tour_destination_id')
        batch_op.drop_column('education_program_id')

    # ### end Alembic commands ###
